name: CI
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install And Build
        run: npm install && npm run build
      - name: DeployGP
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs/.vuepress/dist
      - name: DeployECS
        uses: easingthemes/ssh-deploy@v2
        env:
          ARGS: '-avz --delete'
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ECS_HOST }}
          REMOTE_USER: ${{ secrets.ECS_USER }}
          SOURCE: docs/.vuepress/dist/
          TARGET: /data/apps/docs/knowledge